### ISSUE TITLE
Unable to call hidden pet.

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#138]
@Borlea 

PaperSpigot dev 953 (MC 1.11)
EchoPet dev 27

You are unable to call a hidden pet. Tried both command ```/pet call``` and GUI based clicking with the pet selector. It outputs the message in chat but the pet does not reappear.

**Comment by TheIntelloBox** [comment]
I confirm this bug.

**Comment by Borlea** [comment]
'/pet call
Calls your current Pet to your side
Teleports your current Pet to your location
Useful if the Pet AI is having difficulty locating the owner'
grabbed from the wiki.
A hidden pet is a pet despawned due to a specific reason(like entering a worldguard area that doesn't allow pets) or a player manually removes it.

Pet call is practically useless but its being kept in the plugin for possible future changes.

I'll add a check if the pet is spawned and output a proper message.

**Comment by mibby** [comment]
Perhaps but pet call use to be able to spawn the pet back if it was previously toggled hidden.

**Comment by Borlea** [comment]
This feature got removed because of #108. I'll do a bit of a workaround for call to spawn back pets removed via command.

**Comment by mibby** [comment]
Thanks. Seems to be working fine as of dev 31.
