### ISSUE TITLE
Polarbears/husks different protocol

### ISSUE THREAD

**Issue by AshourAziz** [Borlea/EchoPet#70]
Would there be an option to disable specific mobs if the protocol the client is running does not match when the mob was added.

For example, no client can change the mob to a zombiehusk or spawn a polarbear unless running a 1.10 client.

Running ProtocolSupport I noticed issues with the clients on 1.8 and 1.9 rendering zombies that where glitching everywhere, if this it's not possible or something you believe should not be implemented we could do make do and create something to disable it ourselves, but we thought it would be best added upstream.

**Comment by Borlea** [comment]
I'll most likely not being a protocol version check but maybe the ability to disable certain pets via the config is the best bet..

You could also run an older version of echopet which doesn't contain the new mobs..

**Comment by Borlea** [comment]
In recent commits I've disabled stray/husks displaying in the datamenu if you server isn't 1.10. This is currently the only compatibility I'll support.
Polar bears won't spawn in 1.9 servers so that is already fully functioning.

Everything should work properly if you are running a 1.9 server with support for 1.10 users, but I will not be doing any fixes for 1.10 servers supporting 1.9 users as that is the opposite way you should be doing user support.

I also would like to point out my version of EchoPet only supports 1.9+ I have no intention to do any sort of support for any lower versions.
