### ISSUE TITLE
Teleportation Problems With Pet as Hat

### ISSUE THREAD

**Issue by ryans1230** [Borlea/EchoPet#87]
I've tried other forks that aren't as advanced as this one, and I'm hoping that you can resolve this issue. Basically whenever the pet is on the payer's head, the player cannot be teleported, by any means, not just Essentials, etc. 

No errors, just won't happen (fwiw, Essentials does say "Teleporting...", but player does not actually move).

**Comment by ryans1230** [comment]
Not sure if last nights commit was a full fix, however the latest build still has the same issue.

**Comment by Borlea** [comment]
Due to the fact it is impossible to detect when a player wants to teleport I'm unable to fix this.

PlayerTeleportEvent doesn't get called if a player is a 'vehicle' so if you have a pet has a hat I'm unable to detect if you want to teleport.

This is a limitation on the api, nothing I can do about it.
